# Generated by Django 3.2.8 on 2022-01-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('facebook', models.URLField(blank=True, max_length=700, null=True)),
                ('twitter', models.URLField(blank=True, max_length=700, null=True)),
                ('instagram', models.URLField(blank=True, max_length=700, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=700, null=True)),
                ('whatsapp', models.URLField(blank=True, max_length=700, null=True)),
                ('title_head', models.CharField(max_length=100, null=True)),
                ('body', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700, null=True)),
                ('email', models.EmailField(max_length=700, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('link', models.URLField(blank=True, max_length=700, null=True)),
                ('desc', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_icon', models.CharField(max_length=100, null=True)),
                ('skill_name', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
