# Generated by Django 3.2.8 on 2022-02-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_work_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_icon',
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='image_hover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
