# Generated by Django 3.2.8 on 2022-02-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20220202_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='contact_body',
            field=models.TextField(null=True),
        ),
    ]
